############# German navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Über uns"
url = "/about"
weight = 4

# footer menu
[[footer]]
name = "Über uns"
url = "/about"
weight = 1

[[footer]]
name = "Impressum"
url = "/imprint"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 4
